/**
 * Project Scaffolding
 *
 * Generates a complete Next.js project from a ProductCatalog JSON.
 * The generated project is MCP-UI ready, UCP-compliant, and includes:
 *   - Database schema + seed file
 *   - MCP server with product discovery + checkout tools
 *   - MCP-UI components for rich product display
 *   - UCP checkout session manager
 *   - Merchant center UI
 *   - Commerce feed endpoint
 *   - Well-known UCP profile
 */

import * as fs from "fs";
import * as path from "path";
import type { ProductCatalog } from "../types/product-catalog";
import type { OpenAgentShopConfig } from "../types/config";
import { generateSchemaSource, generateSeedSource } from "../core/schema-builder";
import { generateMcpServerSource } from "../core/mcp-server-builder";
import { generateCheckoutManagerSource } from "../core/ucp-checkout";
import { generateMcpUiSource } from "../core/mcp-ui-renderer";
import { generateFeedAdapterSource, generateFeedRouteSource } from "../core/feed-adapter";
import { generateMcpRouteSource } from "../handlers/mcp-route";
import {
  generateProductsRouteSource,
  generateProductByIdRouteSource,
  generateOrdersRouteSource,
} from "../handlers/merchant-api";
import { generateWellKnownUcpSource } from "../handlers/well-known-ucp";

// ---------------------------------------------------------------------------
// File writing utility
// ---------------------------------------------------------------------------

function writeFile(filePath: string, content: string) {
  const dir = path.dirname(filePath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(filePath, content, "utf-8");
  console.log(`  created: ${path.relative(process.cwd(), filePath)}`);
}

// ---------------------------------------------------------------------------
// Currency source (copied into project)
// ---------------------------------------------------------------------------

function getCurrencySource(): string {
  return `/**
 * UCP-Compliant Currency Utilities
 * Generated by OpenAgentShop SDK
 */

const CURRENCY_EXPONENTS: Record<string, number> = {
  USD: 2, EUR: 2, GBP: 2, SGD: 2, AUD: 2, CAD: 2, CHF: 2,
  CNY: 2, HKD: 2, NZD: 2, SEK: 2, JPY: 0, VND: 0, KRW: 0,
  BHD: 3, KWD: 3, OMR: 3,
};

export function getCurrencyExponent(currency: string): number {
  return CURRENCY_EXPONENTS[currency.toUpperCase()] ?? 2;
}

export function minorToMajor(amount: number, currency: string): number {
  const exp = getCurrencyExponent(currency);
  return amount / Math.pow(10, exp);
}

export function majorToMinor(amount: number, currency: string): number {
  const exp = getCurrencyExponent(currency);
  return Math.round(amount * Math.pow(10, exp));
}

export function formatCurrencyDisplay(amount: number, currency: string, locale = "en-US"): string {
  const major = minorToMajor(amount, currency);
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: currency.toUpperCase(),
    minimumFractionDigits: getCurrencyExponent(currency),
    maximumFractionDigits: getCurrencyExponent(currency),
  }).format(major);
}

export function formatPriceForFeed(amount: number, currency: string): string {
  const major = minorToMajor(amount, currency);
  const exp = getCurrencyExponent(currency);
  return \`\${major.toFixed(exp)} \${currency.toUpperCase()}\`;
}

export function calculateTax(subtotal: number, taxRate: number): number {
  return Math.round(subtotal * taxRate);
}

export function calculateTotals(
  lineItems: Array<{ price: number; quantity: number }>,
  taxRate: number
): { subtotal: number; tax: number; total: number } {
  const subtotal = lineItems.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const tax = calculateTax(subtotal, taxRate);
  return { subtotal, tax, total: subtotal + tax };
}
`;
}

// ---------------------------------------------------------------------------
// Static templates
// ---------------------------------------------------------------------------

function getDbIndexSource(config?: OpenAgentShopConfig): string {
  const provider = config?.database?.provider ?? "neon";
  
  if (provider === "sqlite") {
    const sqlitePath = config?.database?.sqlitePath ?? "./data/shop.db";
    return `import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import * as schema from "./schema";
import * as fs from "fs";
import * as path from "path";

// Ensure data directory exists
const dbPath = ${JSON.stringify(sqlitePath)};
const dir = path.dirname(dbPath);
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

const sqlite = new Database(dbPath);
export const db = drizzle(sqlite, { schema });
`;
  }
  
  if (provider === "neon") {
    return `import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "./schema";

const sql = neon(process.env.DATABASE_URL!);
export const db = drizzle(sql, { schema });
`;
  }
  
  // Generic postgres
  return `import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import * as schema from "./schema";

const client = postgres(process.env.DATABASE_URL!);
export const db = drizzle(client, { schema });
`;
}

function getNextConfigSource(catalog: ProductCatalog): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async headers() {
    return [
      {
        source: "/api/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET, POST, PUT, PATCH, DELETE, OPTIONS" },
          { key: "Access-Control-Allow-Headers", value: "Content-Type, MCP-Session-Id, MCP-Protocol-Version, Authorization" },
          { key: "Access-Control-Expose-Headers", value: "MCP-Session-Id, MCP-Protocol-Version" },
        ],
      },
    ];
  },
};

module.exports = nextConfig;
`;
}

function getDrizzleConfigSource(config?: OpenAgentShopConfig): string {
  const provider = config?.database?.provider ?? "neon";
  
  if (provider === "sqlite") {
    const sqlitePath = config?.database?.sqlitePath ?? "./data/shop.db";
    return `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "sqlite",
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dbCredentials: {
    url: ${JSON.stringify(sqlitePath)},
  },
});
`;
  }
  
  return `import { defineConfig } from "drizzle-kit";

export default defineConfig({
  dialect: "postgresql",
  schema: "./src/db/schema.ts",
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
`;
}

function getTsConfigSource(): string {
  return `{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;
}

function getTailwindConfigSource(): string {
  return `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};

export default config;
`;
}

function getPostcssConfigSource(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;
}

function getGlobalsCssSource(): string {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;
`;
}

function getLayoutSource(catalog: ProductCatalog): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: ${JSON.stringify(catalog.shop.name)},
  description: ${JSON.stringify(catalog.shop.description)},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function getRootPageSource(): string {
  return `import { redirect } from "next/navigation";

export default function Home() {
  redirect("/merchant");
}
`;
}

function getMerchantPageSource(catalog: ProductCatalog): string {
  return `"use client";

import { useEffect, useState } from "react";

interface Product {
  id: number;
  catalogId: string;
  name: string;
  shortDescription: string | null;
  description: string | null;
  price: number;
  discountPrice: number | null;
  active: boolean;
  tier?: string | null;
  currency: string;
}

interface Order {
  id: number;
  productName: string | null;
  userId: string;
  quantity: number;
  totalPrice: number | null;
  status: string;
  createdAt: string;
}

export default function MerchantPage() {
  const [tab, setTab] = useState<"products" | "orders">("products");
  const [products, setProducts] = useState<Product[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [editForm, setEditForm] = useState({ name: "", shortDescription: "", description: "", price: 0, discountPrice: 0 });

  useEffect(() => {
    fetch("/api/merchant/products").then(r => r.json()).then(setProducts);
    fetch("/api/merchant/orders").then(r => r.json()).then(setOrders);
  }, []);

  const formatPrice = (amount: number, currency: string) => {
    const exp = currency === "JPY" ? 0 : 2;
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency, minimumFractionDigits: exp,
    }).format(amount / Math.pow(10, exp));
  };

  const toggleActive = async (id: number, active: boolean) => {
    await fetch(\`/api/merchant/products/\${id}\`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ active }),
    });
    setProducts(products.map(p => p.id === id ? { ...p, active } : p));
  };

  const deleteProduct = async (id: number) => {
    if (!confirm("Are you sure you want to delete this product?")) return;
    await fetch(\`/api/merchant/products/\${id}\`, { method: "DELETE" });
    setProducts(products.filter(p => p.id !== id));
  };

  const openEditModal = (product: Product) => {
    setEditingProduct(product);
    setEditForm({
      name: product.name,
      shortDescription: product.shortDescription || "",
      description: product.description || "",
      price: product.price,
      discountPrice: product.discountPrice || 0,
    });
  };

  const saveProduct = async () => {
    if (!editingProduct) return;
    const res = await fetch(\`/api/merchant/products/\${editingProduct.id}\`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(editForm),
    });
    if (res.ok) {
      const updated = await res.json();
      setProducts(products.map(p => p.id === editingProduct.id ? { ...p, ...updated } : p));
      setEditingProduct(null);
    }
  };

  return (
    <div style={{ maxWidth: 1000, margin: "0 auto", padding: 24 }}>
      <h1 style={{ fontSize: 24, fontWeight: 700, marginBottom: 8 }}>${catalog.shop.name} - Merchant Center</h1>
      <p style={{ color: "#666", marginBottom: 24 }}>${catalog.shop.description}</p>

      {/* Edit Modal */}
      {editingProduct && (
        <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 }}>
          <div style={{ background: "white", padding: 24, borderRadius: 12, width: "100%", maxWidth: 500 }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 16 }}>Edit Product</h2>
            <div style={{ marginBottom: 12 }}>
              <label style={{ display: "block", fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Name</label>
              <input value={editForm.name} onChange={e => setEditForm({ ...editForm, name: e.target.value })} style={{ width: "100%", padding: 8, border: "1px solid #ddd", borderRadius: 6 }} />
            </div>
            <div style={{ marginBottom: 12 }}>
              <label style={{ display: "block", fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Short Description</label>
              <input value={editForm.shortDescription} onChange={e => setEditForm({ ...editForm, shortDescription: e.target.value })} style={{ width: "100%", padding: 8, border: "1px solid #ddd", borderRadius: 6 }} />
            </div>
            <div style={{ marginBottom: 12 }}>
              <label style={{ display: "block", fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Description</label>
              <textarea value={editForm.description} onChange={e => setEditForm({ ...editForm, description: e.target.value })} rows={3} style={{ width: "100%", padding: 8, border: "1px solid #ddd", borderRadius: 6, resize: "vertical" }} />
            </div>
            <div style={{ display: "flex", gap: 12, marginBottom: 12 }}>
              <div style={{ flex: 1 }}>
                <label style={{ display: "block", fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Price (minor units)</label>
                <input type="number" value={editForm.price} onChange={e => setEditForm({ ...editForm, price: parseInt(e.target.value) || 0 })} style={{ width: "100%", padding: 8, border: "1px solid #ddd", borderRadius: 6 }} />
              </div>
              <div style={{ flex: 1 }}>
                <label style={{ display: "block", fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Discount Price</label>
                <input type="number" value={editForm.discountPrice} onChange={e => setEditForm({ ...editForm, discountPrice: parseInt(e.target.value) || 0 })} style={{ width: "100%", padding: 8, border: "1px solid #ddd", borderRadius: 6 }} />
              </div>
            </div>
            <div style={{ display: "flex", gap: 8, justifyContent: "flex-end" }}>
              <button onClick={() => setEditingProduct(null)} style={{ padding: "8px 16px", borderRadius: 6, border: "1px solid #ddd", background: "white", cursor: "pointer" }}>Cancel</button>
              <button onClick={saveProduct} style={{ padding: "8px 16px", borderRadius: 6, border: "none", background: "#1a1a1a", color: "white", cursor: "pointer", fontWeight: 600 }}>Save</button>
            </div>
          </div>
        </div>
      )}

      <div style={{ display: "flex", gap: 8, marginBottom: 24 }}>
        <button
          onClick={() => setTab("products")}
          style={{ padding: "8px 16px", borderRadius: 8, border: "1px solid #ddd", background: tab === "products" ? "#1a1a1a" : "white", color: tab === "products" ? "white" : "#333", cursor: "pointer", fontWeight: 600 }}
        >Products ({products.length})</button>
        <button
          onClick={() => setTab("orders")}
          style={{ padding: "8px 16px", borderRadius: 8, border: "1px solid #ddd", background: tab === "orders" ? "#1a1a1a" : "white", color: tab === "orders" ? "white" : "#333", cursor: "pointer", fontWeight: 600 }}
        >Orders ({orders.length})</button>
      </div>

      {tab === "products" && (
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ borderBottom: "2px solid #eee", textAlign: "left" }}>
              <th style={{ padding: 8 }}>Name</th>
              <th style={{ padding: 8 }}>Price</th>
              <th style={{ padding: 8 }}>Active</th>
              <th style={{ padding: 8 }}>Actions</th>
            </tr>
          </thead>
          <tbody>
            {products.map(p => (
              <tr key={p.id} style={{ borderBottom: "1px solid #f0f0f0" }}>
                <td style={{ padding: 8 }}>
                  <div style={{ fontWeight: 600 }}>{p.name}</div>
                  <div style={{ fontSize: 13, color: "#666" }}>{p.shortDescription}</div>
                </td>
                <td style={{ padding: 8 }}>
                  {p.discountPrice ? (
                    <><span style={{ textDecoration: "line-through", color: "#999" }}>{formatPrice(p.price, p.currency)}</span> {formatPrice(p.discountPrice, p.currency)}</>
                  ) : formatPrice(p.price, p.currency)}
                </td>
                <td style={{ padding: 8 }}>
                  <button
                    onClick={() => toggleActive(p.id, !p.active)}
                    style={{ padding: "2px 8px", borderRadius: 4, border: "none", background: p.active ? "#e8f5e9" : "#fce4ec", color: p.active ? "#2e7d32" : "#c62828", cursor: "pointer", fontSize: 12 }}
                  >{p.active ? "Active" : "Inactive"}</button>
                </td>
                <td style={{ padding: 8, display: "flex", gap: 4 }}>
                  <button onClick={() => openEditModal(p)} style={{ padding: "2px 8px", borderRadius: 4, border: "1px solid #ddd", background: "white", cursor: "pointer", fontSize: 12, color: "#1565c0" }}>
                    Edit
                  </button>
                  <button onClick={() => deleteProduct(p.id)} style={{ padding: "2px 8px", borderRadius: 4, border: "1px solid #ddd", background: "white", cursor: "pointer", fontSize: 12, color: "#c62828" }}>
                    Delete
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}

      {tab === "orders" && (
        <table style={{ width: "100%", borderCollapse: "collapse" }}>
          <thead>
            <tr style={{ borderBottom: "2px solid #eee", textAlign: "left" }}>
              <th style={{ padding: 8 }}>Order ID</th>
              <th style={{ padding: 8 }}>Product</th>
              <th style={{ padding: 8 }}>Customer</th>
              <th style={{ padding: 8 }}>Total</th>
              <th style={{ padding: 8 }}>Status</th>
            </tr>
          </thead>
          <tbody>
            {orders.map(o => (
              <tr key={o.id} style={{ borderBottom: "1px solid #f0f0f0" }}>
                <td style={{ padding: 8, fontWeight: 600 }}>#{o.id}</td>
                <td style={{ padding: 8 }}>{o.productName || "—"}</td>
                <td style={{ padding: 8 }}>{o.userId}</td>
                <td style={{ padding: 8 }}>{o.totalPrice ? formatPrice(o.totalPrice, "USD") : "—"}</td>
                <td style={{ padding: 8 }}>
                  <span style={{ padding: "2px 8px", borderRadius: 4, fontSize: 12, background: o.status === "confirmed" ? "#e8f5e9" : o.status === "canceled" ? "#fce4ec" : "#fff3e0", color: o.status === "confirmed" ? "#2e7d32" : o.status === "canceled" ? "#c62828" : "#e65100" }}>
                    {o.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
`;
}

function getPackageJsonSource(catalog: ProductCatalog, config?: OpenAgentShopConfig): string {
  const port = catalog.shop.port ?? 3000;
  const provider = config?.database?.provider ?? "neon";

  const deps: Record<string, string> = {
    next: "^16.0.0",
    react: "^19.2.4",
    "react-dom": "^19.2.4",
    "@modelcontextprotocol/sdk": "^1.25.3",
    "drizzle-orm": "^0.45.1",
    zod: "^3.25.76",
    tailwindcss: "^3.4.19",
    postcss: "^8.5.6",
    autoprefixer: "^10.4.23",
  };

  if (provider === "sqlite") {
    deps["better-sqlite3"] = "^11.8.0";
  } else if (provider === "neon") {
    deps["@neondatabase/serverless"] = "^1.0.2";
  } else {
    deps["postgres"] = "^3.4.0";
  }

  const devDeps: Record<string, string> = {
    typescript: "^5.9.3",
    "@types/node": "^25.0.10",
    "@types/react": "^19.2.10",
    "@types/react-dom": "^19.2.3",
    "drizzle-kit": "^0.31.8",
  };

  if (provider === "sqlite") {
    devDeps["@types/better-sqlite3"] = "^7.6.13";
  }

  return JSON.stringify(
    {
      name: slugify(catalog.shop.name),
      version: "1.0.0",
      private: true,
      scripts: {
        dev: `next dev -p ${port}`,
        build: "next build",
        start: `next start -p ${port}`,
        lint: "next lint",
        "db:generate": "drizzle-kit generate",
        "db:push": "drizzle-kit push",
        "db:studio": "drizzle-kit studio",
        "db:seed": "npx tsx src/db/seed.ts",
      },
      dependencies: deps,
      devDependencies: devDeps,
    },
    null,
    2
  );
}

function getEnvExampleSource(): string {
  return `# Database connection string
DATABASE_URL=postgresql://user:password@host:5432/dbname

# Public base URL (for feed, checkout links)
NEXT_PUBLIC_BASE_URL=http://localhost:3000
`;
}

function getCheckoutPageSource(): string {
  return `"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

export default function CheckoutPage() {
  const params = useParams();
  const [checkout, setCheckout] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Checkout data would be fetched via the MCP session or API
    setLoading(false);
  }, [params.id]);

  if (loading) return <div style={{ padding: 40, textAlign: "center" }}>Loading checkout...</div>;

  return (
    <div style={{ maxWidth: 480, margin: "40px auto", padding: 24 }}>
      <h1 style={{ fontSize: 20, fontWeight: 700, marginBottom: 16 }}>Checkout</h1>
      <p style={{ color: "#666" }}>Session: {params.id}</p>
      <p style={{ color: "#999", marginTop: 16 }}>
        This checkout page is used as the UCP continue_url for buyer escalation.
        In production, integrate your payment provider here.
      </p>
    </div>
  );
}
`;
}

// ---------------------------------------------------------------------------
// Main scaffold function
// ---------------------------------------------------------------------------

/**
 * Generate a complete Next.js project from a product catalog.
 *
 * @param catalog - The product catalog JSON
 * @param outputDir - Target directory for the project
 * @param config - Optional SDK configuration overrides
 */
export function generateProject(
  catalog: ProductCatalog,
  outputDir: string,
  config?: Omit<OpenAgentShopConfig, "catalog">
): void {
  const fullConfig: OpenAgentShopConfig = { catalog, ...config };
  const root = path.resolve(outputDir);

  console.log(`\nGenerating OpenAgentShop project: ${catalog.shop.name}`);
  console.log(`Output: ${root}\n`);

  // 1. Config files
  writeFile(path.join(root, "package.json"), getPackageJsonSource(catalog, fullConfig));
  writeFile(path.join(root, "tsconfig.json"), getTsConfigSource());
  writeFile(path.join(root, "next.config.js"), getNextConfigSource(catalog));
  writeFile(path.join(root, "drizzle.config.ts"), getDrizzleConfigSource(fullConfig));
  writeFile(path.join(root, "tailwind.config.ts"), getTailwindConfigSource());
  writeFile(path.join(root, "postcss.config.js"), getPostcssConfigSource());
  writeFile(path.join(root, ".env.example"), getEnvExampleSource());

  // 2. Database
  writeFile(path.join(root, "src/db/index.ts"), getDbIndexSource(fullConfig));
  writeFile(path.join(root, "src/db/schema.ts"), generateSchemaSource(catalog));
  writeFile(path.join(root, "src/db/seed.ts"), generateSeedSource(catalog));

  // 3. Lib (currency, MCP server, UCP checkout, MCP-UI, feed)
  writeFile(path.join(root, "src/lib/currency.ts"), getCurrencySource());
  writeFile(path.join(root, "src/lib/mcp-server.ts"), generateMcpServerSource(catalog, fullConfig.mcp));
  writeFile(path.join(root, "src/lib/ucp/checkout-session-manager.ts"), generateCheckoutManagerSource(catalog, fullConfig.ucp));
  writeFile(path.join(root, "src/lib/mcp-ui.ts"), generateMcpUiSource(catalog, fullConfig.ui));
  writeFile(path.join(root, "src/lib/feed-adapter.ts"), generateFeedAdapterSource(catalog, fullConfig.feed));

  // 4. API Routes
  writeFile(path.join(root, "src/app/api/mcp/route.ts"), generateMcpRouteSource(catalog));
  writeFile(path.join(root, "src/app/api/merchant/products/route.ts"), generateProductsRouteSource());
  writeFile(path.join(root, "src/app/api/merchant/products/[id]/route.ts"), generateProductByIdRouteSource());
  writeFile(path.join(root, "src/app/api/merchant/orders/route.ts"), generateOrdersRouteSource());
  writeFile(path.join(root, "src/app/api/feed/route.ts"), generateFeedRouteSource());
  writeFile(path.join(root, "src/app/.well-known/ucp/route.ts"), generateWellKnownUcpSource(catalog, fullConfig.ucp));

  // 5. Pages
  writeFile(path.join(root, "src/app/layout.tsx"), getLayoutSource(catalog));
  writeFile(path.join(root, "src/app/globals.css"), getGlobalsCssSource());
  writeFile(path.join(root, "src/app/page.tsx"), getRootPageSource());
  writeFile(path.join(root, "src/app/merchant/page.tsx"), getMerchantPageSource(catalog));
  writeFile(path.join(root, "src/app/checkout/[id]/page.tsx"), getCheckoutPageSource());

  console.log(`\nProject generated successfully!`);
  console.log(`\nNext steps:`);
  console.log(`  cd ${path.relative(process.cwd(), root)}`);
  console.log(`  cp .env.example .env`);
  console.log(`  # Edit .env with your DATABASE_URL`);
  console.log(`  npm install`);
  console.log(`  npm run db:push`);
  console.log(`  npm run db:seed`);
  console.log(`  npm run dev`);
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
