/**
 * UCP-Compliant Currency Utilities
 * Generated by OpenAgentShop SDK
 */

const CURRENCY_EXPONENTS: Record<string, number> = {
  USD: 2, EUR: 2, GBP: 2, SGD: 2, AUD: 2, CAD: 2, CHF: 2,
  CNY: 2, HKD: 2, NZD: 2, SEK: 2, JPY: 0, VND: 0, KRW: 0,
  BHD: 3, KWD: 3, OMR: 3,
};

export function getCurrencyExponent(currency: string): number {
  return CURRENCY_EXPONENTS[currency.toUpperCase()] ?? 2;
}

export function minorToMajor(amount: number, currency: string): number {
  const exp = getCurrencyExponent(currency);
  return amount / Math.pow(10, exp);
}

export function majorToMinor(amount: number, currency: string): number {
  const exp = getCurrencyExponent(currency);
  return Math.round(amount * Math.pow(10, exp));
}

export function formatCurrencyDisplay(amount: number, currency: string, locale = "en-US"): string {
  const major = minorToMajor(amount, currency);
  return new Intl.NumberFormat(locale, {
    style: "currency",
    currency: currency.toUpperCase(),
    minimumFractionDigits: getCurrencyExponent(currency),
    maximumFractionDigits: getCurrencyExponent(currency),
  }).format(major);
}

export function formatPriceForFeed(amount: number, currency: string): string {
  const major = minorToMajor(amount, currency);
  const exp = getCurrencyExponent(currency);
  return `${major.toFixed(exp)} ${currency.toUpperCase()}`;
}

export function calculateTax(subtotal: number, taxRate: number): number {
  return Math.round(subtotal * taxRate);
}

export function calculateTotals(
  lineItems: Array<{ price: number; quantity: number }>,
  taxRate: number
): { subtotal: number; tax: number; total: number } {
  const subtotal = lineItems.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const tax = calculateTax(subtotal, taxRate);
  return { subtotal, tax, total: subtotal + tax };
}
